// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: auler/v1/auler.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Auler_ListUser_FullMethodName = "/v1.Auler/ListUser"
)

// AulerClient is the client API for Auler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Auler 定义了一个 Auler RPC 服务.
type AulerClient interface {
	// 罗列用户，为简单模式（无数据流）
	ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
}

type aulerClient struct {
	cc grpc.ClientConnInterface
}

func NewAulerClient(cc grpc.ClientConnInterface) AulerClient {
	return &aulerClient{cc}
}

func (c *aulerClient) ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, Auler_ListUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AulerServer is the server API for Auler service.
// All implementations must embed UnimplementedAulerServer
// for forward compatibility.
//
// Auler 定义了一个 Auler RPC 服务.
type AulerServer interface {
	// 罗列用户，为简单模式（无数据流）
	ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error)
	mustEmbedUnimplementedAulerServer()
}

// UnimplementedAulerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAulerServer struct{}

func (UnimplementedAulerServer) ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (UnimplementedAulerServer) mustEmbedUnimplementedAulerServer() {}
func (UnimplementedAulerServer) testEmbeddedByValue()               {}

// UnsafeAulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AulerServer will
// result in compilation errors.
type UnsafeAulerServer interface {
	mustEmbedUnimplementedAulerServer()
}

func RegisterAulerServer(s grpc.ServiceRegistrar, srv AulerServer) {
	// If the following call pancis, it indicates UnimplementedAulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auler_ServiceDesc, srv)
}

func _Auler_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AulerServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auler_ListUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AulerServer).ListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auler_ServiceDesc is the grpc.ServiceDesc for Auler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Auler",
	HandlerType: (*AulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _Auler_ListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auler/v1/auler.proto",
}
