apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auler # 资源标签
  name: auler # 资源名称
spec:
  replicas: 2 # 副本数
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: auler
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auler
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - auler
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /opt/auler/bin/auler
        - --config=/etc/auler/auler.yaml
        image: "HeapSoil/auler-amd64:c904829"
        name: auler
        ports:
        - containerPort: 8443
          name: secure
          protocol: TCP
        - containerPort: 6060
          name: insecure
          protocol: TCP
        - containerPort: 9090
          name: rpc 
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6060
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 6060
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 6060
            scheme: HTTP
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/auler/auler.yaml
          name: auler
          subPath: auler.yaml
        - mountPath: /etc/auler/cert
          name: auler-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
            {}
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: auler.yaml
            path: auler.yaml
          name: auler
        name: auler
      - configMap:
          defaultMode: 420
          name: auler-cert
        name: auler-cert