apiVersion: v1
kind: Service
metadata:
  labels:
    app: auler
  name: auler
spec:
  ports:
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: http
    protocol: TCP
    port: 6060
    targetPort: 6060
  - name: rpc
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: auler
  sessionAffinity: None
  type: ClusterIP